### ISSUE TITLE
Remove reliance on . in @INC

### ISSUE THREAD

**Issue by haarg** [moose/Dist-Zilla-Plugin-Conflicts#7]
Currently, the code injected into Makefile.PL/Build.PL relies on `.` being in `@INC`, trying to require a filename like `lib/Moose/Conflicts.pm`.  It has [been proposed](https://rt.perl.org/Public/Bug/Display.html?id=127810) that `.` be removed from `@INC` without an environment variable set, possibly controlled by a build option and possibly just changed by default without a deprecation cycle.

As a preventative measure, the code this module inserts should stop relying on `.`, possibly by loading the module as `./lib/Moose/Conflicts.pm`, or possibly by locally adding lib to `@INC`.

**Comment by autarch** [comment]
Fixed in 0.19. Thanks!
